### PR TITLE
Correct UserGuide.md bugs

### LINKED ISSUE #154: Minor edits to UserGuide.md
1. Grammatical errors
2. Styling errors
3. Final Ui that our application shows
4. Title of our application when rendered
5. More planned enhancements on `updatephoto` command

### PR DESCRIPTION
**Pull request by limjunxian1**
Refer to #154 for what this PR does. Closes #154

### CODE REVIEW

**Review by conradsoon — COMMENTED** [review]
- Markbind builds locally.
- Image replaced correctly.
- Jar renamed to `CampusConnect.jar` correctly.

**Review by conradsoon — COMMENTED** [review]
**Warnings / Error Cases** for features will be shown in a **yellow box** with this **exclamation mark icon** :fa-solid-exclamation: . These clarify cases **which will are** expected to display errors to users, or explain enhancements that will be implemented in future releases of CampusConnect.

Which will are should be which are (Line 77)

**Review by conradsoon — CHANGES_REQUESTED** [review]
Warnings / Error Cases for features will be shown in a yellow box with this exclamation mark icon :fa-solid-exclamation: . These clarify cases which will are expected to display errors to users, or explain enhancements that will be implemented in future releases of CampusConnect.

Which will are should be which are (UserGuide.md Line 77)

**Comment by limjunxian1** [comment]
> Warnings / Error Cases for features will be shown in a yellow box with this exclamation mark icon :fa-solid-exclamation: . These clarify cases which will are expected to display errors to users, or explain enhancements that will be implemented in future releases of CampusConnect.
> 
> Which will are should be which are (UserGuide.md Line 77)

thank you for pointing that out! fixed in ef1db11c

**Review by conradsoon — APPROVED** [review]
Thanks for fixing up the UserGuide. Have taken a read through again and don't spot any other grammatical/language mistakes. LGTM.

**Pull request merged**
